In [4]:
import torch
import torch.nn as nn
import numpy as np
from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt
from tqdm import tqdm

In [26]:
m = 1000

X, y = make_blobs(n_samples=m,
                  n_features=3,
                  shuffle=True,
                  random_state=42)

train_size = 750

X_train, y_train = X[:train_size], y[:train_size]
X_test, y_test = X[train_size:], y[train_size:]

print(X_train[0])

X_train.shape, y_train.shape, X_test.shape, y_test.shape

[-1.62313406  8.87720831  4.84001326]


((750, 3), (750,), (250, 3), (250,))

In [210]:
def printt(x): print(['{:f}'.format(i) for i in x.detach().numpy()])

torch.manual_seed(42)

layers = nn.Sequential(
    nn.Linear(in_features=3, out_features=3))
    #nn.Softmax(dim=0))


    
X_train_tensor = torch.from_numpy(X_train).type(torch.float32)
y_train_tensor = torch.Tensor(y_train).type(torch.long)


# single

i = 5

samples = X_train_tensor[i].unsqueeze(0)

preds = layers(samples)

loss_fn = nn.CrossEntropyLoss()

loss = loss_fn(preds, y_train_tensor[i].unsqueeze(0))

print("Logits:  ", preds.detach().numpy().squeeze())
print("Softmax: ", torch.softmax(preds, dim=1).detach().numpy().squeeze())
print("Loss:    ", loss.detach().numpy())
print("\n")


# multi

i = 15

samples = X_train_tensor[:i]
labels = y_train_tensor[:i]
logits = layers(samples)
loss = loss_fn(logits, labels)

print("Logits:\n", logits)
print(f"\nSoftmax {logits.shape}:\n", torch.softmax(logits, dim=1))
print("\nLoss:\n", loss)
print("\n")

print(torch.softmax(preds, dim=1))
print(loss)

Logits:   [-1.7134843 -5.1125574  6.2606854]
Softmax:  [3.44118191e-04 1.14949935e-05 9.99644399e-01]
Loss:     0.00035565728


Logits:
 tensor([[ 2.4593, -0.9181,  6.0376],
        [-1.2193,  1.2717, -5.5731],
        [ 1.9715, -0.9329,  6.3642],
        [-0.6470, -4.9998,  7.2019],
        [ 0.9929, -2.1822,  7.1968],
        [-1.7135, -5.1126,  6.2607],
        [ 0.3726, -1.4776,  6.0889],
        [-1.4856, -4.9399,  6.3059],
        [ 1.8181, -1.5287,  6.3792],
        [-0.1748, -3.9132,  5.9726],
        [-1.0460, -5.4438,  6.8412],
        [ 1.8234, -1.5400,  7.9136],
        [ 2.0170, -1.0839,  5.7875],
        [-0.4587, -5.0183,  6.1394],
        [ 2.1092, -1.1774,  6.0311]], grad_fn=<AddmmBackward0>)

Softmax torch.Size([15, 3]):
 tensor([[2.7139e-02, 9.2640e-04, 9.7193e-01],
        [7.6420e-02, 9.2260e-01, 9.8257e-04],
        [1.2207e-02, 6.6876e-04, 9.8712e-01],
        [3.9003e-04, 5.0199e-06, 9.9961e-01],
        [2.0172e-03, 8.4300e-05, 9.9790e-01],
        [3.4412e-04,