In [7]:
import torch
import torch.nn as nn

In [21]:
for i in range(10): print("Hello, World!")

Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!


In [22]:
# We define a helper function to calculate convolutions. It initializes the
# convolutional layer weights and performs corresponding dimensionality
# elevations and reductions on the input and output
def comp_conv2d(conv2d, X):
    # (1, 1) indicates that batch size and the number of channels are both 1
    X = X.reshape((1, 1) + X.shape)
    Y = conv2d(X)
    # Strip the first two dimensions: examples and channels
    return Y.reshape(Y.shape[2:])

# 1 row and column is padded on either side, so a total of 2 rows or columns
# are added
conv2d = nn.LazyConv2d(1, kernel_size=3, padding=1)
X = torch.rand(size=(8, 8))
comp_conv2d(conv2d, X).shape

/Users/dav/dev/doml/mlenv/lib/python3.11/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


torch.Size([8, 8])

In [23]:
# We use a convolution kernel with height 5 and width 3. The padding on either
# side of the height and width are 2 and 1, respectively
conv2d = nn.LazyConv2d(1, kernel_size=(5, 3), padding=(2, 1))
comp_conv2d(conv2d, X).shape

/Users/dav/dev/doml/mlenv/lib/python3.11/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


torch.Size([8, 8])

In [35]:
print(torch.zeros((12,10)))
print(torch.zeros(5,3).t())

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [27]:
print(X)

tensor([[5.4998e-01, 7.4759e-01, 8.6146e-01, 7.7801e-01, 7.5484e-01, 2.8589e-01,
         8.2610e-01, 5.7424e-01],
        [3.2821e-01, 1.0461e-01, 4.8217e-01, 7.5393e-01, 3.9137e-01, 9.5403e-01,
         5.1609e-02, 5.4073e-04],
        [6.3630e-01, 3.5149e-01, 3.7537e-01, 8.6627e-01, 6.6676e-01, 3.7598e-01,
         9.2719e-01, 7.7095e-01],
        [6.2878e-01, 1.8897e-01, 6.1460e-01, 9.3262e-01, 6.8621e-01, 3.2978e-02,
         4.6026e-01, 5.1107e-01],
        [9.3550e-01, 8.1566e-01, 7.0087e-01, 7.0465e-01, 7.6487e-01, 6.2976e-01,
         6.8111e-02, 3.6827e-01],
        [4.7964e-01, 4.7639e-01, 3.8373e-01, 4.5165e-01, 7.9012e-01, 4.2803e-02,
         7.8236e-01, 1.0151e-01],
        [1.4627e-01, 3.7886e-01, 7.5258e-01, 7.4041e-01, 2.5602e-01, 4.4527e-01,
         1.3955e-01, 7.4787e-01],
        [7.4207e-01, 9.8411e-01, 3.6007e-02, 6.5831e-01, 3.8225e-01, 2.9037e-02,
         3.1727e-01, 9.6749e-01]])
