In [1]:
import torch
import torch.nn as nn

In [2]:
(torch.tensor([1,2,4,5]) * torch.tensor([1,2,3,4])).sum()

tensor(37)

In [3]:
(torch.tensor([0,1,3,4]) * torch.tensor([0,1,2,3])).sum()

tensor(19)

In [149]:
# Create a 2D convolutional layer with a 2x2 kernel
conv_layer = nn.Conv2d(in_channels=3, out_channels=4, kernel_size=(2,2), bias=False)

# Access the initial values of the kernel weights
kernel_weights = conv_layer.weight.data

print(kernel_weights)

tensor([[[[-0.0753,  0.0990],
          [ 0.0900, -0.1622]],

         [[ 0.0770, -0.2020],
          [ 0.0593, -0.2863]],

         [[ 0.1126, -0.1835],
          [ 0.1405,  0.2883]]],


        [[[-0.0521,  0.2090],
          [ 0.2072,  0.0451]],

         [[ 0.1263,  0.2847],
          [ 0.1379,  0.0883]],

         [[-0.0203, -0.2250],
          [ 0.0394,  0.1093]]],


        [[[ 0.1684, -0.1288],
          [ 0.0646, -0.2780]],

         [[-0.1661, -0.1632],
          [ 0.2182, -0.0087]],

         [[ 0.1561, -0.0320],
          [-0.0235, -0.2177]]],


        [[[ 0.2691, -0.2126],
          [-0.0521,  0.2184]],

         [[ 0.0986,  0.0449],
          [-0.2074, -0.2554]],

         [[ 0.0555,  0.2657],
          [ 0.2691,  0.2859]]]])


In [152]:
np.sum(np.array([[[-0.0753,  0.0990],
          [ 0.0900, -0.1622]],

         [[ 0.0770, -0.2020],
          [ 0.0593, -0.2863]],

         [[ 0.1126, -0.1835],
          [ 0.1405,  0.2883]]]))

-0.042599999999999916

In [150]:
c1 = torch.tensor([[[1,1],[1,1]]])
c2 = torch.tensor([[[1,1],[1,1]]])
x = torch.concat((c1, c2))
print(x)

conv_layer(x.type(torch.float))

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]])


RuntimeError: Given groups=1, weight of size [4, 3, 2, 2], expected input[1, 2, 2, 2] to have 3 channels, but got 2 channels instead

In [140]:
import numpy as np

# Provided weights as a NumPy array
weights = np.array(
    [
        [
            [
                [-0.1148, -0.2670],
                [-0.2279, -0.2192]
            ],
            [
                [0.0874, -0.0510],
                [-0.2232, 0.1391]
            ]
        ],
        [
            [
                [0.3019, -0.1097],
                [0.2187, 0.0668]
            ],
            [
                [0.3392, -0.1770],
                [-0.1581, 0.1339]
            ]
        ],
        [
            [
                [0.2033, -0.1580],
                [-0.1814, 0.0550]
            ],
            [
                [-0.2848, 0.1708],
                [-0.2199, -0.0607]
            ]
        ]
    ]
)
print(weights[2], weights[2].shape)
print(weights.shape)

# Define an example input tensor
input_tensor = np.array(
    [
        [
            [1, 1],
            [1, 1]
        ],
        [
            [1, 1],
            [1, 1]
        ]
    ]
)

# Function to calculate the output for one output channel
def calculate_output_channel(input_tensor, weights):
    output = np.zeros((input_tensor.shape[0] - 1, input_tensor.shape[1] - 1))
    # weights shape (3,2,2,2)
    for i in range(weights.shape[1]): # 2
        for j in range(weights.shape[2]): # 2
            output += input_tensor[i:i+2, j:j+2] * weights[0, i, j]
    return output

# Calculate the output for each output channel
output_channel1 = calculate_output_channel(input_tensor, weights[0])
output_channel2 = calculate_output_channel(input_tensor, weights[1])
output_channel3 = calculate_output_channel(input_tensor, weights[2])

# Print the results
print("Output Channel 1:")
print(output_channel1)
print("\nOutput Channel 2:")
print(output_channel2)
print("\nOutput Channel 3:")
print(output_channel3)


[[[ 0.2033 -0.158 ]
  [-0.1814  0.055 ]]

 [[-0.2848  0.1708]
  [-0.2199 -0.0607]]] (2, 2, 2)
(3, 2, 2, 2)


ValueError: non-broadcastable output operand with shape (1,1) doesn't match the broadcast shape (2,2,2)