In [1]:
import torch
import torch.nn as nn

In [2]:
(torch.tensor([1,2,4,5]) * torch.tensor([1,2,3,4])).sum()

tensor(37)

In [3]:
(torch.tensor([0,1,3,4]) * torch.tensor([0,1,2,3])).sum()

tensor(19)

In [146]:
# Create a 2D convolutional layer with a 2x2 kernel
conv_layer = nn.Conv2d(in_channels=3, out_channels=3, kernel_size=(2,2), bias=False)

# Access the initial values of the kernel weights
kernel_weights = conv_layer.weight.data

print(kernel_weights)

tensor([[[[-0.2115,  0.0264],
          [-0.0280, -0.0082]],

         [[-0.0165, -0.1082],
          [ 0.2588, -0.2024]],

         [[ 0.1329, -0.2659],
          [ 0.1921, -0.2376]]],


        [[[ 0.0786,  0.2416],
          [ 0.0149, -0.0611]],

         [[-0.0414, -0.2423],
          [-0.1153,  0.0435]],

         [[ 0.1330, -0.1805],
          [-0.2572, -0.2583]]],


        [[[-0.0912,  0.0342],
          [-0.2425,  0.1726]],

         [[ 0.1277, -0.1058],
          [-0.0497,  0.2467]],

         [[-0.1761, -0.0160],
          [ 0.0642, -0.2743]]]])


In [141]:
c1 = torch.tensor([[[1,1],[1,1]]])
c2 = torch.tensor([[[1,1],[1,1]]])
x = torch.concat((c1, c2))
print(x)

conv_layer(x.type(torch.float))

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]])


tensor([[[-0.8764]],

        [[ 0.6159]],

        [[-0.4757]]], grad_fn=<SqueezeBackward1>)

In [140]:
import numpy as np

# Provided weights as a NumPy array
weights = np.array(
    [
        [
            [
                [-0.1148, -0.2670],
                [-0.2279, -0.2192]
            ],
            [
                [0.0874, -0.0510],
                [-0.2232, 0.1391]
            ]
        ],
        [
            [
                [0.3019, -0.1097],
                [0.2187, 0.0668]
            ],
            [
                [0.3392, -0.1770],
                [-0.1581, 0.1339]
            ]
        ],
        [
            [
                [0.2033, -0.1580],
                [-0.1814, 0.0550]
            ],
            [
                [-0.2848, 0.1708],
                [-0.2199, -0.0607]
            ]
        ]
    ]
)
print(weights[2], weights[2].shape)
print(weights.shape)

# Define an example input tensor
input_tensor = np.array(
    [
        [
            [1, 1],
            [1, 1]
        ],
        [
            [1, 1],
            [1, 1]
        ]
    ]
)

# Function to calculate the output for one output channel
def calculate_output_channel(input_tensor, weights):
    output = np.zeros((input_tensor.shape[0] - 1, input_tensor.shape[1] - 1))
    # weights shape (3,2,2,2)
    for i in range(weights.shape[1]): # 2
        for j in range(weights.shape[2]): # 2
            output += input_tensor[i:i+2, j:j+2] * weights[0, i, j]
    return output

# Calculate the output for each output channel
output_channel1 = calculate_output_channel(input_tensor, weights[0])
output_channel2 = calculate_output_channel(input_tensor, weights[1])
output_channel3 = calculate_output_channel(input_tensor, weights[2])

# Print the results
print("Output Channel 1:")
print(output_channel1)
print("\nOutput Channel 2:")
print(output_channel2)
print("\nOutput Channel 3:")
print(output_channel3)


[[[ 0.2033 -0.158 ]
  [-0.1814  0.055 ]]

 [[-0.2848  0.1708]
  [-0.2199 -0.0607]]] (2, 2, 2)
(3, 2, 2, 2)


ValueError: non-broadcastable output operand with shape (1,1) doesn't match the broadcast shape (2,2,2)